apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-streamlit-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-streamlit-new
  template:
    metadata:
      labels:
        app: ts-streamlit-new
    spec:
      containers:
      - name: ts-streamlit-new
        image: krithiksundar/ts-streamlit:latest2
        ports:
        - containerPort: 8501
