apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-streamlit-new3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-streamlit-new3
  template:
    metadata:
      labels:
        app: ts-streamlit-new3
    spec:
      containers:
      - name: ts-streamlit-new3
        image: krithiksundar/ts-streamlit:latest5
        ports:
        - containerPort: 8501
