apiVersion: v1
kind: Service
metadata:
  name: ts-streamlit-service-new3
spec:
  type: NodePort
  selector:
    app: ts-streamlit-new3
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30030   # accessible port
