apiVersion: v1
kind: Service
metadata:
  name: ts-streamlit-service
spec:
  type: NodePort
  selector:
    app: ts-streamlit
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30080   # accessible port
