apiVersion: v1
kind: Service
metadata:
  name: ts-streamlit-service-new1
spec:
  type: NodePort
  selector:
    app: ts-streamlit-new1
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30010   # accessible port
