apiVersion: v1
kind: Service
metadata:
  name: ts-streamlit-service-new
spec:
  type: NodePort
  selector:
    app: ts-streamlit-new
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30090   # accessible port
